/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthorInformation: typeof import('./src/components/AuthorInformation/index.vue')['default']
    Banner: typeof import('./src/components/Banner/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    IconArrowRight: typeof import('./src/components/icons/IconArrowRight.vue')['default']
    Label: typeof import('./src/components/Label/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupportBanner: typeof import('./src/components/SupportBanner/index.vue')['default']
  }
}
